// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Mon Oct 10 18:34:56 2022

clock_480p clock_480p_inst
(
	.clk_100m(clk_100m_sig) ,	// input  clk_100m_sig
	.rst(rst_sig) ,	// input  rst_sig
	.clk_pix(clk_pix_sig) ,	// output  clk_pix_sig
	.clk_pix_5x(clk_pix_5x_sig) ,	// output  clk_pix_5x_sig
	.clk_pix_locked(clk_pix_locked_sig) 	// output  clk_pix_locked_sig
);

